Jira/flc 213 litecoin lib
fluencesh/fluence.libs.monorepo pull request #1
Opened 2018-11-21 13:32 UTC by gr3w2

Litecoin lib was migrated

2018-11-28 08:37 UTC, grimelion approved these changes

2018-11-30 09:45 UTC, andapplctr requested changes
Check the ocmments

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.bitcoin/config/test.json
> +                        "host": "94.130.216.246",
remove IP, and provide local env var instead

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.litecoin/package.json
> +  "description": "Bitcoin Blockchain Plugin",
Litecoin BLockchain plugin

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.litecoin/sonar-project.properties
> +sonar.organization=applicature
is it correct org?

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.litecoin/src/services/blockchain/litecoin.ts
> +        return AvailableNetwork.LITECOIN === network || AvailableNetwork.TEST_NET === network;
Litecoin Testnet?

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.services/package.json
> +        "@applicature/synth.dynamodb": "^2.0.21",
Do we use dynamodb?

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.services/src/dao/dynamodb/webhook.action.dao.ts
> +export class DynamodbWebhookActionDao extends DynamoDBDao<Scheme.WebhookActionItem> implements WebhookActionDao {
Do we use DynamoDB?

2018-11-30 09:45 UTC, andrew-zubko-applicature commented on packages/fluence.lib.services/src/models/index.ts
> +export class WebhookDaoActionItem {
Do we use DynamoDB?

2018-11-30 10:15 UTC, closed without merging